pipeline{
    agent any

    environment{
        PATH = "/opt/flutter/bin:${PATH}"
    }

    stages{

        stage('Clone Git Repo'){
            steps{
                script{
                    def gitUrl='https://github.com/mrabdulla3/DevOps_Flutter.git'

                    checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: gitUrl,
                    ]]
                ])
                }

            }

        }
        stage('Get Dependencies'){
            steps{
                sh 'flutter pub get'
            }
        }

        stage('build'){
            steps{
                sh '''
                ls
                echo "This is build section"
                '''
            }

        }

        stage('Deploy'){
            input{
                message 'Deploy?'
                ok 'Do it'
                parameters{
                    string(name:'TARGET_ENVIRONMENT',defaultValue: 'empty',description : 'Target Environment Variable')
                }
               
            }
             steps{
                    echo "Deployed ${TARGET_ENVIRONMENT}"
                }
        }
    }
}