pipeline{
    agent any

    environment{
        PATH = "/opt/flutter/bin:${PATH}"
    }

    stages{

        stage('Clone Git Repo'){
            steps{
                script{
                    def gitUrl='https://github.com/mrabdulla3/DevOps_Flutter.git'

                    checkout([$class: 'GitSCM', 
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: gitUrl,
                    ]]
                ])
                }

            }

        }
        stage('Get Dependencies'){
            steps{
                sh 'flutter pub get'
            }
        }

        stage('build'){
                parallel{
                    stage('Stage-1'){
                        steps{
                            echo "Parallel stage 1"
                        }
                    }

                     stage('Stage-2'){
                        steps{
                            echo "Parallel stage 2"
                        }
                    }
                     stage('Stage-3'){
                        steps{
                            echo "Parallel stage 3"
                        }
                    }
            }

        }

        stage('Deploy'){
            input{
                message 'Deploy?'
                ok 'Do it'
                parameters{
                    string(name:'TARGET_ENVIRONMENT',defaultValue: 'empty',description : 'Target Environment Variable')
                }
               
            }
             steps{
                    echo "Deployed ${TARGET_ENVIRONMENT}"
                }
        }

       stage('Publish') {
            steps {
                archiveArtifacts artifacts: 'build/app/outputs/flutter-apk/app-release.apk', fingerprint: true
            }
        }
    }
}